# Site settings
title: The Fellowship of The Ring
email: noreply@codeastra.com
description: > # this means to ignore newlines until "baseurl:"
  The Fellowship of the Ring was formed as a brotherhood among members of the various Free People of Middle-earth.
  It's purpose was to take the One Ring to Mordor that it might be cast into thte fires of Mount Doom, the mountain in which it was forged, so that it woud be destroyed, this would ultimately kill Dark Lord Souron.
baseurl: "/fotr" # the subpath of your site, e.g. /blog/
url: "http://www.codeastra.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
